### ISSUE TITLE
nip 04

### ISSUE THREAD

**Issue by asoltys** [fiatjaf/nak#36]
was missing it for constructing nwc events

**Comment by fiatjaf** [comment]
You mean it isn't missing anymore?

**Comment by fiatjaf** [comment]
Now it isn't. `nak encrypt --nip04` and `nak decrypt --nip04` should work. 

Please install this from source and test because I ended up changing the way keys are handled across the entire app to get this working in a non-trash way and would be good to have some more hands on it before I make a release.

**Comment by asoltys** [comment]
cool thanks! tested nip04 encrypt/decrypt and they worked as expected. I'll test some other things later
